### ISSUE TITLE
xash3d (android) shield controller

### ISSUE THREAD

**Issue by rmderoode** [cyndis/shield-controller-config#1]
I just signed up for github for one problem, im trying to play the best game ever (half-life 1 on android) with my shield controller.
Everything works, but i cant get the right trigger and left trigger to work. I googled my *ss off, maybe you could help me, just found your config file. but still cant bind the two buttons. 
To be honest i dont know if this is the way to ask people here for help, but thanks in advance.

Greetings from holland,

Machiel de Roode

**Comment by cyndis** [comment]
Sorry, I don't know anything about how the joystick system on Android works - I actually only use my controller on Linux. Good luck, though :) (and yes, HL is awesome..)
